# Generated by Django 4.0.2 on 2022-02-25 14:36

import applications.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(help_text='Для выделения первой буквы/слова использовать <span class="firstcharacter"></span>', verbose_name='Контент')),
                ('image', models.ImageField(upload_to=applications.core.models.PathAndRename('about/about/image'), verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
