# Generated by Django 4.0.2 on 2022-02-25 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order'], 'verbose_name': 'слайдеры', 'verbose_name_plural': 'слайдеры'},
        ),
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='slider',
            name='preference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='sliders.sliderpreference', verbose_name='настройки'),
            preserve_default=False,
        ),
    ]
